apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogIlpHdHlZWE51ZVd0b09tZG9jRjkxYVVoNWNWZDFTVFZQVlZZeVozbGhPREEzY2psMWIybFZSRFpSUWt3MFdVeFZhMmc9IgogICAgICAgICAgICAgICAgfQogICAgICAgIH0sCgkiY3VycmVudENvbnRleHQiOiAiY29saW1hIgp9Cg==
type: kubernetes.io/dockerconfigjson
